version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:860061945305:task-definition/apigateway:3"
        LoadBalancerInfo:
          ContainerName: "authorization"
          ContainerPort: "9001"
        PlatformVersion: "LATEST"
